name: dipl_admin
description: "Admin app for courier system."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  decimal: ^3.0.2
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  http: ^1.2.2
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
